#! /usr/bin/env python3
'''
ROS wrapper for task planner.
'''

from __future__ import print_function

import uuid
import rospy
from actionlib import SimpleActionServer

from ropod.structs.task import TaskRequest
from task_planner.metric_ff_interface import MetricFFInterface
from task_planner.knowledge_base_interface import KnowledgeBaseInterface

from task_planner_ros_wrapper.msg import TaskPlannerPredicate, TaskPlannerFluent
from task_planner_ros_wrapper.msg import TaskPlannerFluentValue, TaskPlannerPlanAction
from task_planner_ros_wrapper.msg import TaskPlannerPlanResult
from task_planner_ros_wrapper.srv import TaskPlannerQueryKB, TaskPlannerUpdateKB

from task_planner_ros_wrapper.update_kb_handler import UpdateKBHandler
from task_planner_ros_wrapper.query_kb_handler import QueryKBHandler
from task_planner_ros_wrapper.plan_action_handler import PlanActionHandler

NODE = 'task_planner'

class TaskPlannerROSInterface():

    """ROS wrapper for task planner."""

    def __init__(self):
        planner_params = rospy.get_param('~planner_params', None)
        plan_file_path = rospy.get_param('~plan_file_path', '/tmp')
        self.kb_interface = KnowledgeBaseInterface(planner_params['kb_database_name'])
        self.planner = MetricFFInterface(
            planner_params['kb_database_name'],
            planner_params['domain_file'],
            planner_params['planner_cmd'],
            plan_file_path,
            debug=True)
        rospy.logdebug("Initialised planner")

        rospy.Service('~update_kb', TaskPlannerUpdateKB, self._service_update_kb_request)
        self._update_kb_handler = UpdateKBHandler(self.kb_interface)
        rospy.Service('~query_kb', TaskPlannerQueryKB, self._service_query_kb_request)
        self._query_kb_handler = QueryKBHandler(self.kb_interface)
        self._plan_server = SimpleActionServer('~plan', TaskPlannerPlanAction, self._service_plan_request, False)
        self._plan_action_handler = PlanActionHandler(self.planner)
        self._plan_server.start()

        rospy.loginfo("Initialised TaskPlannerROSInterface")

    def _service_update_kb_request(self, req):
        """Service request for updating task planner's knowledge base

        :req: TaskPlannerUpdateKBRequest
        :returns: TaskPlannerUpdateKBResponse

        """
        return self._update_kb_handler.get_safe_response(req)

    def _service_query_kb_request(self, req):
        """Service request for querying task planner's knowledge base

        :req: TaskPlannerQueryKBRequest
        :returns: TaskPlannerQueryKBResponse

        """
        return self._query_kb_handler.get_safe_response(req)

    def _service_plan_request(self, req):
        """Service request for planning using task planner's planner interface

        :req: TaskPlannerPlanGoal
        :returns: None

        """
        response = self._plan_action_handler.get_safe_result(req)
        if response.plan_found:
            self._plan_server.set_succeeded(response)
        else:
            self._plan_server.set_aborted(response)

if __name__ == "__main__":
    rospy.init_node(NODE)
    TASK_PLANNER_ROS_INTERFACE = TaskPlannerROSInterface()
    rospy.spin()
    rospy.loginfo("[%s] Stopped", NODE)
