# Service to update task planner's knowledge base

ROSPredicate[] facts_to_add
ROSPredicate[] facts_to_remove

ROSFluent[] fluents_to_add
ROSFluent[] fluents_to_remove

ROSPredicate[] goals_to_add
ROSPredicate[] goals_to_remove
---
bool success
